# Generated by Django 5.1.4 on 2025-02-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='task_type',
            field=models.CharField(blank=True, choices=[('PERSONAL', 'Personal'), ('MEETING', 'Meeting'), ('PROJECT', 'Project'), ('DEADLINE', 'Deadline'), ('REMINDER', 'Reminder')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TASK_COMPLETED', 'Task Completed'), ('TASK_COMMENT', 'Task Comment'), ('TASK_ASSIGNED', 'Task Assigned'), ('FILE_UPLOAD', 'File Upload'), ('MEETING_STARTING', 'Meeting Starting'), ('REMINDER', 'Reminder')], max_length=20),
        ),
    ]
