# Generated by Django 5.1.4 on 2025-01-28 21:40

import task_app.modeldefinitions.taskmodels
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0004_task_completion_date_task_last_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(upload_to=task_app.modeldefinitions.taskmodels.task_attachment_path),
        ),
    ]
