# Generated by Django 5.1.4 on 2025-02-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TASK_COMPLETED', 'Task Completed'), ('TASK_COMMENT', 'Task Comment'), ('TASK_ASSIGNED', 'Task Assigned'), ('FILE_UPLOAD', 'File Upload'), ('MEETING_REMINDER', 'Meeting Reminder'), ('DEADLINE_APPROACHING', 'Deadline Approaching'), ('REMINDER', 'Reminder')], max_length=20),
        ),
    ]
